### ISSUE TITLE
Create a test for account update operation

### ISSUE THREAD

**Issue by marcialvieira** [christophersanborn/ledger-app-bitshares#11]
Hi everyone, I'm trying to encode this example, can anyone help me if I'm understanding it correctly?

https://github.com/bitshares/python-bitshares/blob/master/tests/test_transactions.py#L311,L340

```
serialize_transaction { "ref_block_num": 35221, "ref_block_prefix": 3092364852, "expiration": "2018-12-04T03:54:15", "operations": [[ 6,{ "fee": {"amount": 1467634, "asset_id": "1.3.0"}, "account": "1.2.15", "owner": { "weight_threshold": 1, "account_auths": [["1.2.96086", 1]], "key_auths": [ ["BTS6pbVDAjRFiw6fkiKYCrkz7PFeL7XNAfefrsREwg8MKpJ9VYV9x", 1] ], "address_auths": [] }, "active": { "weight_threshold": 1, "account_auths": [["1.2.96086", 1]], "key_auths": [ ["BTS8CemMDjdUWSV5wKotEimhK6c4dY7p2PdzC2qM1HpAP8aLtZfE7", 1] ], "address_auths": [] }, "new_options": { "memo_key": "BTS5TPTziKkLexhVKsQKtSpo4bAv5RnB8oXcG4sMHEwCcTf3r7dqE", "voting_account": "1.2.5", "num_witness": 0, "num_committee": 0, "votes": [], "extensions": [] }, "extensions": {}, "prefix": "BTS" } ] ], "extensions": []}
```

### Result:
```
...f264160000000000000f010100000001d6ee0501000102fe8cc11cc8251de6977636b55c1ab8a9d12b0b26154ac78e56e7c4257d8bcf69010000010100000001d6ee0501000103b453f46013fdbccb90b09ba169c388c34d84454a3b9fbec68d5a7819a734fca001000001024ab336b4b14ba6d881675d1c782912783c43dbbe31693aa710ac1896bd7c3d61050000000000...
```

### Decoding:

| Field | Data |
|--:|:--|
| fee.amount <Q | f264160000000000 |
| fee.asset_id | 00 |
| account | 0f |
| owner presence | 01 |
| owner.weight_threshold <I | 01000000 |
| owner.account_auths count | 01 |
| owner.account_auths[0] | d6ee05 |
| owner.account_auths[1] <H | 0100 |
| owner.key_auths count | 01 |
| owner.key_auths[0] | 02fe8cc11cc8251de6977636b55c1ab8a9d12b0b26154ac78e56e7c4257d8bcf69 |
| owner.key_auths[1] <H | 0100 |
| owner.address_auths count | 00 |
| active presence | 01 |
| active.weight_threshold <I | 01000000 |
| active.account_auths count | 01 |
| active.account_auths[0] | d6ee05 |
| active.account_auths[1] <H | 0100 |
| owner.key_auths count | 01 |
| active.key_auths[0] | 03b453f46013fdbccb90b09ba169c388c34d84454a3b9fbec68d5a7819a734fca0 |
| active.key_auths[1] <H | 0100 |
| owner.address_auths count | 00 |
| new_options presence | 01 |
| memo_key | 024ab336b4b14ba6d881675d1c782912783c43dbbe31693aa710ac1896bd7c3d61 |
| voting_account | 05 |
| num_witness | 00 |
| num_committee | 00 |
| votes | 00 |
| new_options.extensions | 00 |
| extensions | 00 |

**Comment by christophersanborn** [comment]
Here's my decoding of the serialized form:

(At quick glance, looks pretty identical)
```
uint64 | fee.Amount     | f264160000000000
varint | fee.AssetIId   | 00
varint | account iId    | 0f
 bool  | owner present  | 01
uint32 | weight thresh  |   01000000
varint | acct_auths len |   01
varint |       acct iId |     d6ee05
uint16 |         weight |     0100
varint |  key_auths len |   01
pubkey |         pubkey |     02fe8cc11cc8251de6977636b55c1ab8a9d12b0b26154ac78e56e7c4257d8bcf69
unit16 |         weight |     0100
varint | addr_auths len |   00
 bool  | active present | 01
uint32 | weight thresh  |   01000000
varint | acct_auths len |   01
varint |       acct iId |     d6ee05
uint16 |         weight |     0100
varint | key_auths len  |   01
pubkey |         pubkey |     03b453f46013fdbccb90b09ba169c388c34d84454a3b9fbec68d5a7819a734fca0
unit16 |         weight |     0100
varint | addr_auths len |   00
 bool  | new_o present  | 01
pubkey |       memo key |   024ab336b4b14ba6d881675d1c782912783c43dbbe31693aa710ac1896bd7c3d61
varint | voting_account |   05
uint16 |  num witnesses |   0000
uint16 |  num committee |   0000
varint |      votes len |   01
uint32 |        vote Id |     02a70000
varint |    new_o extns |   00
varint | operatn extens | 00
```

**Comment by marcialvieira** [comment]
Thanks for helping me in the chat, without your help, I probably would need more time.

Commit [5cfbf3b](https://github.com/christophersanborn/ledger-app-bitshares/commit/5cfbf3b6a90d00045b6776474b2e352271a10058).
