### ISSUE TITLE
What exactly are the fields present in a serialized Bitshares Transaction?

### ISSUE THREAD

**Issue by christophersanborn** [christophersanborn/ledger-app-bitshares#4]
This should be somewhere in the existing Bitshares docs.  Either find and link here or reproduce relevant specs here.

This is needed by #1 and #2 because it effects serialization and decoding of Bitshares Tx's.

**Comment by clockworkgr** [comment]
https://steemit.com/steem/@xeroc/steem-transaction-signing-in-a-nutshell

**Comment by christophersanborn** [comment]
This can be answered by looking in python-graphenelib [signed-transactions.py#L67](https://github.com/xeroc/python-graphenelib/blob/e318080597edc5cad4f9c840769ddc6de1421203/graphenebase/signedtransactions.py#L67)

In short, the format is:

| Field | Data |
|--:|:--|
| ref_block_num | 2 bytes |
| ref_block_prefix |  4 bytes |
| expiration | 4 bytes |
| num_operations | varint |
| _operations_ | _operations go here, if any_ |
| num_extensions | varint |
| _extensions_ | _extensions go here, if any_ |
| num_signatures | varint |
| _signatures_ | _sigs go here, if any_ |

**Comment by christophersanborn** [comment]
Moved over to Wiki.
